### ISSUE TITLE
sizes_df_lin  --> y_in_first_frame

### ISSUE THREAD

**Issue by RonnyFoerster** [RonnyFoerster/NanoObjectDetection#33]
Not sure who build this in. @MonaNis 

is it possible that this corresponds to the drift corrected position rather than the position in the rawdata?

**Comment by MonaNis** [comment]
It was me, that's correct. If you want to get out the position before drift correction, you have to pass the trajectory data before drift correction ('t4' or similar) to the CalcDiameter.Main() function like this:
`nd.CalcDiameter.Main(t6_final, ParameterJsonFile, obj_all, t_beforeDrift=t4)`
If you don't pass the 't_beforeDrift' argument, only the positions after drift correction appear in the results' matrix.

**Comment by RonnyFoerster** [comment]
maybe change the default_auswertung.py ?

**Comment by RonnyFoerster** [comment]
I don't like that we use the drift trajectory as start_x and start_y in case t_beforeDrift is not given. I think we should give here 0, 1 or "t_beforeDrift  not given". Otherwise you look in the rawdata at the wrong position and dont know it. @MonaNis

**Comment by MonaNis** [comment]
I think we should leave it as it is, because in the case of low drift, the information contained is still valuable. It always depends on what exactly you want to do with the results...
At the moment, it's nowhere defined that "x in first frame" (y, resp.) should correspond 1:1 with the rawframes. I find it quite obvious that the function can only work with the information it receives. 

But I agree that default_auswertung.py has to be updated - the next commit will include this.

**Comment by MonaNis** [comment]
I also added some words on this to the documentation of the CalcDiameter.Main function. Which is anyways still under construction... but it should be more clear now what to expect from the "t_beforeDrift" parameter, I hope. 

Close this or still disagreement here?
